name: Main

on:
- push
- pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
      DATABASE_URL: postgres://postgres:@localhost:5432/postgres
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:11.5
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: sudo apt-get -yqq install libpq-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
